#!/usr/bin/env python3

from simple_term_menu import TerminalMenu
import os
import platform
import sys
import Wolverine_Functions as wf

# This part is used to detect the OS you use and clear the console.
OperatingSystem = platform.system()

if OperatingSystem == "Windows":
    os.system("cls")
else:
    os.system("clear")
# ------------------------------------------------------------------

def main():
    print("Wolverine needs sudo to work properly...")
    os.system("sudo clear")
    #if (sys.argv[0] == "-q"):
    #    os.system("cat /etc/WolverineFramework/logo_quiet")
    #else:
    #    os.system("cat /etc/WolverineFramework/logo") 
    os.system("cat /home/theo/Documents/Github/WolverinePython/logo_quiet")
    print("---------------------------------")
    print("What hacking process do you want to perform ?")
    print("---------------------------------\n")
    options = ["Network Scanning", "Man in The Middle Attack", "DoS / DDoS", "Bruteforce", "Launch Metasploit", "Doxing from a phone number", "Scan wordpress vulnerabilities", "Hide your MAC Adress with a fake MAC Adress", "Take remote control of a device", "Quit Wolverine"]
    terminal_menu = TerminalMenu(options)
    menu_entry_index = terminal_menu.show()
    UserChoice = options[menu_entry_index]
    print(UserChoice)
    wf.AttackPerformed(UserChoice)



if __name__ == "__main__":
    main()